#
# Copyright (c) 2019 by Delphix. All rights reserved.
#
id: 0b284512-edee-4a9f-95b1-980f093cd4dd
name: sc:mongopy
externalVersion: 0.0.6
buildNumber: 0.0.6
hostTypes:
  - UNIX
entryPoint: mongopy:plugin
srcDir: src/
schemaFile: ./schema.json
pluginType: STAGED
language: PYTHON27
